import {
  Column,
  CreateDateColumn,
  Entity,
  OneToOne,
  PrimaryGeneratedColumn,
  UpdateDateColumn
} from 'typeorm'
import { v4 as uuid } from 'uuid'
import { PasswordRecovery } from '../password-recovery/password-recovery.entity'

/**
 * Represents the currently logged in user in the app.
 */
@Entity({ name: 'users' })
export class User {
  /**
   * UserId: an autogenerated UUID.
   */
  @PrimaryGeneratedColumn('uuid')
  id: string

  /**
   * Username retrieved from local sign up or from the social login.
   */
  @Column()
  username: string

  /**
   * User's email retrieved from local sign up or from the social login.
   */
  @Column({ unique: true })
  email: string

  /**
   * User's hashed password along with the random hashed salt separated by a dot. The hashed salt
   * helps prevent Rainbow Table Attack. This field is optional, if the user is logged in using
   * the OpenID.
   */
  @Column({ nullable: true })
  hashedPassword?: string

  /**
   * UserId retrieved from Google's OpenID feature, if the user has logged in using Google.
   */
  @Column({ nullable: true })
  googleId?: string

  /**
   * UserId retrieved from facebook's OpenID feature, if the user has logged in using Facebook.
   */
  @Column({ nullable: true })
  facebookId?: string

  /**
   * UserId retrieved from Apple's OpenID feature, if the user has logged in using Apple.
   */
  @Column({ nullable: true })
  appleId?: string

  /**
   * A random string to join with the JWT secret key. Changing this causes the change in the
   * JWT secret key with which the tokens were created. As a result, the tokens stored on all
   * devices of this user become invalid. Helpful for logging out the user from all other devices.
   */
  @Column()
  tokenInvalidator: string

  /**
   * Date and time when the user was created. It is set automatically when the new user is inserted.
   */
  @CreateDateColumn()
  createdAt: Date

  /**
   * Date and time when the user was last updated. It is set automatically each time you call save()
   * function of the entity.
   */
  @UpdateDateColumn()
  updatedAt: Date

  /**
   * Represents the recovery code used for resetting the password.
   *
   * onDelete: specifies how foreign key should behave when referenced object is deleted. We don't
   * use it here, because we don't need the passwordRecoveryId field on this side. We manage the
   * relation from the PasswordRecovery entity.
   *
   * The 'cascade: true' is a typeorm feature and not a database feature unlike onDelete. It allows
   * us to save the entity along with its related entity in just one save() call.
   */
  @OneToOne(() => PasswordRecovery, (passwordRecovery) => passwordRecovery.user)
  passwordRecovery?: PasswordRecovery

  /**
   * Generates a new tokenInvalidator. This logs the user out of all devices as tokens signed with
   * JWT secret + tokenInvalidator will change.
   */
  invalidateAllTokens() {
    this.tokenInvalidator = uuid()
  }

  isSocial(): boolean {
    return !!(this.googleId || this.appleId || this.facebookId)
  }
}
